Revert "Replace repository select with combobox (#61)"
This reverts commit e2eb65d460779ff391b3bbba8408d323183717e0.

It breaks multi branch pipelines with SVN repositories.
This is due to illegal URLs that are generated for SVN
repositories which create the following exception:

Proposing simple_svn
Opening conection to http://localhost:8081/scm/repo/http:/
ERROR: Could not communicate with Subversion server
org.tmatesoft.svn.core.SVNException: svn: E175002: OPTIONS of '/scm/repo/http:': 400 Bad Request (http://localhost:8081)
svn: E175002: OPTIONS request failed on '/scm/repo/http:'